version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"      
      - "8080:8080"  
    command:
      - "--api.insecure=true"               
      - "--providers.docker=true"           
      - "--entrypoints.web.address=:80"     
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" 

  backend:
    image: traefik/whoami
    deploy:
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
