version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"    
      - "8080:8080"
    command:
      - "--api.insecure=true"                 
      - "--providers.docker=true"             
      - "--entrypoints.web.address=:80"       
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" 

  whoami:
    image: "traefik/whoami" 
    container_name: "whoami"
    labels:
      - "traefik.enable=true"                 
      - "traefik.http.routers.whoami.rule=Host(`localhost`)" 
